# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 08:47
from __future__ import unicode_literals

import re

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

from words import constants as words_constants


def load_inital_data(apps, schema_editor):
    Word = apps.get_model('words', 'Word')

    data = []
    for line in open('words/fixtures/initial-word-data.txt', 'r').readlines():
        word, ipa, native_hi = [
            w.strip() for w in ':'.join(re.split(r'=>', line)).split(':')
        ]
        data.append({
            'text': word,
            'pronunciation': {
                'ipa': {
                    'native': ipa,
                },
                'native_hi': {
                    'native': native_hi
                }
            }
        })

    for word_data in data:
        Word.objects.create(
            text=word_data['text'],
            language=words_constants.ENGLISH_US,
            pronunciation=word_data['pronunciation'],
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en_US', 'English (United States)'), ('en_GB', 'English (United Kingdom)'), ('hi', 'Hindi')], max_length=7)),
                ('text', models.CharField(max_length=200)),
                ('disambiguation', models.CharField(blank=True, max_length=200)),
                ('pronunciation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en_US', 'English (United States)'), ('en_GB', 'English (United Kingdom)'), ('hi', 'Hindi')], max_length=7)),
                ('text', models.TextField(blank=True)),
                ('antonyms', models.ManyToManyField(related_name='antonyms', to='words.Word')),
                ('meanings', models.ManyToManyField(related_name='meanings', to='words.Word')),
                ('synonyms', models.ManyToManyField(related_name='synonyms', to='words.Word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='root_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='words.WordRelation'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('language', 'text', 'disambiguation')]),
        ),
        migrations.RunPython(load_inital_data),
    ]
